"""HF-41: a unit emitted after the battery named the battery's disposable workspace as the
daemon's home. Before cut 2, qualify.emit generated the unit in the battery's process after
battery.Workspace had set SPARK_DAEMON_HOME to the workspace's home, so Environment=,
ReadWritePaths= and every expanded "~" path pointed into /tmp/spark-battery-*/home.

Run from the pattern root: python3 -B evidence/v5/hf41_repro.py
Prints the unit's SPARK_DAEMON_HOME and output path, and whether they are the author's."""
import os
import sys
import tempfile

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, root)
author_home = tempfile.mkdtemp(prefix="hf41-author-home-")
os.environ["SPARK_DAEMON_HOME"] = author_home
from spark_daemon import judge, unitgen  # noqa: E402

manifest = os.path.join(root, "examples", "meminfo-watch", "manifest.json")
profile = "validate" if "DB-03" in judge.profile_ids("validate") else "precheck"   # the short run
j = judge.run(profile, manifest)                                      # builds the battery workspace
if hasattr(judge, "unit_from_report"):
    _, text = judge.unit_from_report(judge.report(j))                 # cut 2: projected from the report
    how = "judge.unit_from_report(judge.report(j)) (cut 2)"
else:
    text = unitgen.generate(j.m, root=root, **j.unit_options)         # what qualify.emit did after the run
    how = "unitgen.generate after the run (as qualify.emit did, r4.11)"
lines = [ln for ln in text.splitlines() if ln.startswith(("Environment=SPARK_DAEMON_HOME=", "ReadWritePaths="))]
print(f"generated by: {how}")
print(f"author's home: {author_home}")
for ln in lines:
    print(ln)
ok = all(author_home in ln for ln in lines)
print("RESULT:", "the unit names the author's home" if ok else "DEFECT: the unit names the battery workspace")
sys.exit(0 if ok else 1)
