"""spark-daemon scaffold: a better blank page, nothing more.

Writes manifest.json, daemon.py and candidate.json for a new daemon into an empty folder.
The result validates and prechecks as written (it watches the host name, a value that
almost never changes), so whoever fills it in - a person or a generator - starts from a
known-good state and every later failure is their own change. It is deliberately not
`spark-new daemon`: it installs nothing, grants nothing, and its candidate.json says
producer kind "script" until the author regenerates it with `spark-daemon envelope`.
"""

import json
import os

from . import MANIFEST_SCHEMA
from . import manifest as mf
from .handoff import ENVELOPE_NAME, make_envelope

DAEMON_TEMPLATE = '''"""{name}: {purpose}

Generated by `spark-daemon scaffold` against daemon contract {contract_version}
(`spark-daemon describe` prints the full contract). Replace the observation below.

The rules, in brief (the contract is authoritative):
- sense(ctx) is the only function with I/O, and only through ctx: read_text, list_dir,
  stat, disk_usage, now_utc. A daemon runs no program (contract 5).
  Every path must be inside the manifest's "reads"; anything else raises ctx.NotAllowed
  and stops the daemon (exit 78) even if you catch it.
- decide(prev, snapshot) is pure: previous snapshot (None after a start) in, a list of
  (event_type, payload) out. Event types must be declared in manifest.json's
  ledger.event_types. Payloads are plain data: no floats (use integers with a unit).
- digest(snapshot, recent) is optional and pure: [(title, [(label, value), ...]), ...].
- Imports only from the contract's allowed list (re, json, collections, ...). No open(),
  print(), getattr(), private attributes, globals, or calls at import time except simple
  constructors such as re.compile().
"""

import re

# Placeholder observation: the host name. Replace with what this daemon watches.
HOSTNAME_PATH = "/proc/sys/kernel/hostname"
_PRINTABLE = re.compile(r"[^A-Za-z0-9._-]")


def sense(ctx):
    """The only function that performs I/O, and only through ctx."""
    try:
        text = ctx.read_text(HOSTNAME_PATH, max_bytes=256)
    except ctx.Missing:
        return {{"hostname": None}}
    return {{"hostname": _PRINTABLE.sub("?", text.strip())[:64]}}


def decide(prev, snapshot):
    """Pure: returns [(event_type, payload), ...] using only declared event types."""
    if prev is None:
        return [("OBSERVATION_BASELINE", {{"hostname": snapshot["hostname"]}})]
    if prev["hostname"] != snapshot["hostname"]:
        return [("OBSERVATION_CHANGED", {{"before": prev["hostname"], "after": snapshot["hostname"]}})]
    return []


def digest(snapshot, recent):
    """Pure: sections of (label, value) rows; the skeleton renders and contains them."""
    changes = [r for r in recent if r["event_type"] == "OBSERVATION_CHANGED"][-5:]
    rows = [(f"seq {{r['seq']}}", f"{{r['payload']['before']}} to {{r['payload']['after']}}") for r in changes]
    return [("Now", [("Host name", snapshot["hostname"])]),
            ("Recent changes", rows or [("Changes", "none recorded since this run started")])]
'''


def manifest_template(name: str, purpose: str, unit: str) -> dict:
    run_as = {"unit": "user"} if unit == "user" else {"unit": "system", "user": _service_user(name)}
    return {
        "manifest_schema": MANIFEST_SCHEMA,
        "name": name,
        "version": "0.1.0",
        "purpose": purpose,
        "daemon_class": "observe",
        "trigger": {"kind": "poll", "interval_seconds": 60},
        "reads": ["/proc/sys/kernel/hostname"],
        "output_dir": f"~/spark-daemons/{name}",
        "network": {"mode": "none"},
        "run_as": run_as,
        "resources": {"cpu_weight": 10, "cpu_budget_bp": 100, "memory_max_mb": 64, "tasks_max": 8,
                      "io_class": "idle"},
        "cycle_budget_seconds": 30,      # the longest one whole cycle may take; the watchdog derives from it
        "blind_limit_seconds": 3600,     # set above the longest legitimate unsettled period
        "ledger": {"record_max_bytes": 8192, "event_types": ["OBSERVATION_BASELINE", "OBSERVATION_CHANGED"]},
        "digest": {"enabled": True, "max_bytes": 8192},
    }


def _service_user(name: str) -> str:
    user = f"spark-{name}"[:32].rstrip("-")
    return user


def scaffold(directory: str, *, name: str, purpose: str | None = None, unit: str = "system") -> list:
    """Write the three files; refuses a non-empty folder. Returns the paths written."""
    if not mf.NAME_RE.fullmatch(name or ""):
        raise ValueError("name must be 3-40 characters: lowercase letters, digits and '-', starting with a letter")
    purpose = purpose or f"Scaffolded observe-only daemon {name}; replace this purpose line."
    if not mf.PURPOSE_RE.fullmatch(purpose):
        raise ValueError("purpose must be one line of 10-200 plain characters")
    if unit not in ("system", "user"):
        raise ValueError("unit must be 'system' or 'user'")
    if os.path.exists(directory) and os.listdir(directory):
        raise FileExistsError(f"{directory} is not empty; scaffold never overwrites")
    os.makedirs(directory, exist_ok=True)
    from .contract import CONTRACT_VERSION
    data = manifest_template(name, purpose, unit)
    mf.parse(data, os.path.join(directory, "manifest.json"))       # the template must always validate
    manifest_path = os.path.join(directory, "manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2)
        fh.write("\n")
    code_path = os.path.join(directory, "daemon.py")
    with open(code_path, "w", encoding="utf-8") as fh:
        fh.write(DAEMON_TEMPLATE.format(name=name, purpose=purpose, contract_version=CONTRACT_VERSION))
    envelope = make_envelope(directory, producer_kind="script", producer_id="spark-daemon scaffold",
                             intent=purpose)
    envelope_path = os.path.join(directory, ENVELOPE_NAME)
    with open(envelope_path, "w", encoding="utf-8") as fh:
        json.dump(envelope, fh, indent=2)
        fh.write("\n")
    return [manifest_path, code_path, envelope_path]
