"""Generate a sandboxed systemd unit and a human install plan from a manifest.

The generator never installs, enables or starts anything. Its output is text for review.
Default is a system unit with a dedicated user: Observer v0.3 section 4 notes that Ubuntu
24.04 restricts unprivileged user namespaces, so many sandbox directives only take effect
reliably in system units. User units are generated with the same directives and a warning;
verify them with `systemd-analyze --user security` before relying on them.
"""

import os
import re

from . import VERSION
from .paths import expand, home

# The three Landlock syscalls sit in systemd's @sandbox group, which @system-service does
# NOT include (checked with `systemd-analyze syscall-filter` on systemd 255). Without this
# line every one of them fails with EPERM under the unit, landlock.abi_version() reports it
# as unavailable, and runtime.py refuses to start (exit 78, PD-15): the daemon could never
# run as installed. Found in r3; the r2 battery could not catch it because it never runs
# the daemon under the unit's seccomp filter.
LANDLOCK_SYSCALLS = "landlock_create_ruleset landlock_add_rule landlock_restrict_self"
# Characters a path may carry into a unit file unquoted: no spaces (argument splitting),
# no "%" (specifiers), no quotes, backslashes, control characters or ";" (ExecStart syntax).
_UNIT_SAFE_PATH = re.compile(r"^/[A-Za-z0-9._/+@-]*$")


class UnitError(ValueError):
    """A path cannot be written into a unit file safely."""


def _unit_path(label, path) -> str:
    if not _UNIT_SAFE_PATH.match(path):
        raise UnitError(f"{label} {path!r} contains characters that are unsafe in a systemd unit")
    return path

REQUIRED_DIRECTIVES = (
    "Type=notify", "NotifyAccess=main", "WatchdogSec=", "Restart=on-failure", "UMask=0077",
    "NoNewPrivileges=yes", "ProtectSystem=strict", "ProtectHome=read-only", "ReadWritePaths=",
    "InaccessiblePaths=", "PrivateTmp=yes", "PrivateDevices=yes", "PrivateNetwork=yes",
    "IPAddressDeny=any", "RestrictAddressFamilies=AF_UNIX", "CapabilityBoundingSet=",
    "SystemCallFilter=@system-service", f"SystemCallFilter={LANDLOCK_SYSCALLS}",
    "MemoryDenyWriteExecute=yes", "RestrictNamespaces=yes",
    "LockPersonality=yes", "RestrictSUIDSGID=yes", "ProtectKernelTunables=yes",
    "ProtectKernelModules=yes", "ProtectControlGroups=yes", "CPUWeight=", "MemoryMax=",
    "TasksMax=",
)


def unit_name(m) -> str:
    return f"spark-daemon-{m.name}.service"


def generate(m, *, root: str, python: str = "/usr/bin/python3") -> str:
    out = _unit_path("output_dir", expand(m.output_dir))
    reads = [_unit_path("read path", expand(p)) for p in m.reads]
    ro = [p for p in reads if not (p.startswith("/proc/") or p.startswith("/sys/"))]
    deny = [_unit_path("denied path", expand(p)) for p in m.all_deny]
    manifest_path = _unit_path("manifest path", os.path.abspath(m.path))
    entry = _unit_path("pattern root", os.path.join(os.path.abspath(root), "bin", "spark-daemon"))
    python = _unit_path("python", python)
    daemon_home = _unit_path("SPARK_DAEMON_HOME", home())
    system = m.run_as.unit == "system"
    lines = [
        f"# Generated by spark-daemon-pattern {VERSION} from {manifest_path}",
        f"# manifest sha256 {m.sha256}",
        "# Do not edit by hand: change the manifest and regenerate. Review before installing.",
    ]
    if not system:
        lines.append("# WARNING: user unit. On Ubuntu 24.04 many sandbox directives need user namespaces;"
                     " verify with systemd-analyze --user security before relying on them.")
    lines += [
        "",
        "[Unit]",
        f"Description=Spark daemon {m.name}: {m.purpose.replace('%', '%%')}",
        "StartLimitIntervalSec=300",
        "StartLimitBurst=5",
        "",
        "[Service]",
        "Type=notify",
        "NotifyAccess=main",
        f"ExecStart={python} -I -B {entry} run --manifest {manifest_path}",
    ]
    if system:
        lines.append(f"User={m.run_as.user}")
        lines.append(f"Group={m.run_as.user}")
    lines += [
        f"Environment=SPARK_DAEMON_HOME={daemon_home}",
        f"WatchdogSec={m.watchdog_seconds}",
        f"TimeoutStartSec={max(60, m.watchdog_seconds)}",
        "TimeoutStopSec=30",
        "Restart=on-failure",
        "RestartSec=10",
        "UMask=0077",
        "",
        "# Resources",
        f"CPUWeight={m.resources.cpu_weight}",
        f"MemoryMax={m.resources.memory_max_mb}M",
        f"TasksMax={m.resources.tasks_max}",
        f"IOSchedulingClass={m.resources.io_class}",
        "Nice=10",
        "",
        "# Filesystem: everything read-only except the output directory; denied paths invisible",
        "ProtectSystem=strict",
        "ProtectHome=read-only",
        f"ReadWritePaths={out}",
    ]
    if ro:
        lines.append("ReadOnlyPaths=" + " ".join(f"-{p}" for p in ro))
    lines += [
        "InaccessiblePaths=" + " ".join(f"-{p}" for p in deny),
        "PrivateTmp=yes",
        "PrivateDevices=yes",
        "ProtectProc=invisible",
        "",
        "# Network: none (manifest network.mode = none)",
        "PrivateNetwork=yes",
        "IPAddressDeny=any",
        "RestrictAddressFamilies=AF_UNIX",
        "",
        "# Privileges and kernel",
        "NoNewPrivileges=yes",
        "CapabilityBoundingSet=",
        "AmbientCapabilities=",
        "ProtectKernelTunables=yes",
        "ProtectKernelModules=yes",
        "ProtectKernelLogs=yes",
        "ProtectControlGroups=yes",
        "ProtectClock=yes",
        "ProtectHostname=yes",
        "RestrictNamespaces=yes",
        "RestrictRealtime=yes",
        "RestrictSUIDSGID=yes",
        "LockPersonality=yes",
        "MemoryDenyWriteExecute=yes",
        "RemoveIPC=yes",
        "KeyringMode=private",
        "SystemCallArchitectures=native",
        "SystemCallFilter=@system-service",
        "# Landlock (runtime.py applies it at start-up); @system-service does not include @sandbox",
        f"SystemCallFilter={LANDLOCK_SYSCALLS}",
        "SystemCallFilter=~@privileged @resources",
        "SystemCallErrorNumber=EPERM",
        "",
        "[Install]",
        f"WantedBy={'multi-user.target' if system else 'default.target'}",
        "",
    ]
    return "\n".join(lines)


# Syscalls the runtime makes during start-up that a seccomp filter could silently break.
STARTUP_SYSCALLS = ("landlock_create_ruleset", "landlock_add_rule", "landlock_restrict_self",
                    "prctl", "flock", "fsync")


def resolve_syscall_filter(unit_text: str, expand_group) -> tuple:
    """(allowed, denied) syscall sets from the unit's SystemCallFilter= lines, with groups
    expanded by expand_group("@name") -> iterable of syscall names (for example from
    `systemd-analyze syscall-filter`). Positive lines are merged (a union); lines starting
    with "~" are subtracted."""
    allowed, denied = set(), set()
    for line in unit_text.splitlines():
        line = line.strip()
        if not line.startswith("SystemCallFilter="):
            continue
        value = line.split("=", 1)[1]
        target = allowed
        if value.startswith("~"):
            target, value = denied, value[1:]
        for item in value.split():
            if item.startswith("@"):
                target.update(expand_group(item))
            else:
                target.add(item)
    return allowed, denied


def lint(unit_text: str) -> list:
    """Directives every generated unit must carry. Returns the missing ones."""
    present = [line.strip() for line in unit_text.splitlines() if not line.lstrip().startswith("#")]
    return [d for d in REQUIRED_DIRECTIVES if not any(line.startswith(d) for line in present)]


def install_plan(m, *, root: str, python: str = "/usr/bin/python3") -> str:
    name = unit_name(m)
    out = expand(m.output_dir)
    reads = [expand(p) for p in m.reads]
    lines = [
        f"# Install plan for {name}. Nothing below has been run.",
        "# A human runs it after the battery passes and activation is approved (Class C).",
        f"# Generated by spark-daemon-pattern {VERSION}; manifest sha256 {m.sha256}.",
        "",
    ]
    entry = os.path.join(root, "bin", "spark-daemon")
    lines += [
        "# 0. The conformance battery must print RESULT: PASS for this exact manifest and daemon.py:",
        f"python3 -I -B {entry} battery --manifest {os.path.abspath(m.path)}",
        "",
    ]
    if m.run_as.unit == "system":
        user = m.run_as.user
        lines += [
            "# The service user must be able to read the pattern and this daemon's folder, and reach the",
            "# output directory. Installing the pattern and daemon folders root-owned and read-only (for",
            "# example under /opt) is simplest; an output directory under a home directory also needs",
            "# traverse (x) permission on each parent. Decide these per path.",
            f"sudo useradd --system --no-create-home --shell /usr/sbin/nologin {user}",
            f"sudo install -d -m 0700 -o {user} -g {user} {out}",
            "# Read access: the service user must be able to read each path below. Decide per path;",
            "# never grant anything under ~/spark-core/data or ~/spark-governance/history.",
        ]
        lines += [f"#   {p}" for p in reads]
        lines += [
            f"python3 -I -B {os.path.join(root, 'bin', 'spark-daemon')} unit --manifest {os.path.abspath(m.path)} > {name}",
            f"sudo install -m 0644 {name} /etc/systemd/system/{name}",
            f"sudo systemd-analyze security --threshold=20 {name}",
            "sudo systemctl daemon-reload",
            f"sudo systemctl enable --now {name}",
            f"systemctl status {name}    # READY and the last watchdog ping",
        ]
    else:
        lines += [
            "loginctl enable-linger \"$USER\"    # so the unit survives logout (Observer v0.3 section 3.4)",
            f"python3 -I -B {os.path.join(root, 'bin', 'spark-daemon')} unit --manifest {os.path.abspath(m.path)} > ~/.config/systemd/user/{name}",
            f"systemd-analyze --user security --threshold=20 {name}",
            "systemctl --user daemon-reload",
            f"systemctl --user enable --now {name}",
        ]
    return "\n".join(lines)
