"""Generate a sandboxed systemd unit and a human install plan from a manifest.

The generator never installs, enables or starts anything. Its output is text for review.
Default is a system unit with a dedicated user: Observer v0.3 section 4 notes that Ubuntu
24.04 restricts unprivileged user namespaces, so many sandbox directives only take effect
reliably in system units. User units are generated with the same directives and a warning;
verify them with `systemd-analyze --user security` before relying on them.
"""

import os

from . import VERSION
from .paths import expand, home

REQUIRED_DIRECTIVES = (
    "Type=notify", "NotifyAccess=main", "WatchdogSec=", "Restart=on-failure", "UMask=0077",
    "NoNewPrivileges=yes", "ProtectSystem=strict", "ProtectHome=read-only", "ReadWritePaths=",
    "InaccessiblePaths=", "PrivateTmp=yes", "PrivateDevices=yes", "PrivateNetwork=yes",
    "IPAddressDeny=any", "RestrictAddressFamilies=AF_UNIX", "CapabilityBoundingSet=",
    "SystemCallFilter=@system-service", "MemoryDenyWriteExecute=yes", "RestrictNamespaces=yes",
    "LockPersonality=yes", "RestrictSUIDSGID=yes", "ProtectKernelTunables=yes",
    "ProtectKernelModules=yes", "ProtectControlGroups=yes", "CPUWeight=", "MemoryMax=",
    "TasksMax=",
)


def unit_name(m) -> str:
    return f"spark-daemon-{m.name}.service"


def generate(m, *, root: str, python: str = "/usr/bin/python3") -> str:
    out = expand(m.output_dir)
    reads = [expand(p) for p in m.reads]
    ro = [p for p in reads if not (p.startswith("/proc/") or p.startswith("/sys/"))]
    deny = [expand(p) for p in m.all_deny]
    manifest_path = os.path.abspath(m.path)
    entry = os.path.join(root, "bin", "spark-daemon")
    system = m.run_as.unit == "system"
    lines = [
        f"# Generated by spark-daemon-pattern {VERSION} from {manifest_path}",
        f"# manifest sha256 {m.sha256}",
        "# Do not edit by hand: change the manifest and regenerate. Review before installing.",
    ]
    if not system:
        lines.append("# WARNING: user unit. On Ubuntu 24.04 many sandbox directives need user namespaces;"
                     " verify with systemd-analyze --user security before relying on them.")
    lines += [
        "",
        "[Unit]",
        f"Description=Spark daemon {m.name}: {m.purpose.replace('%', '%%')}",
        "StartLimitIntervalSec=300",
        "StartLimitBurst=5",
        "",
        "[Service]",
        "Type=notify",
        "NotifyAccess=main",
        f"ExecStart={python} -I -B {entry} run --manifest {manifest_path}",
    ]
    if system:
        lines.append(f"User={m.run_as.user}")
        lines.append(f"Group={m.run_as.user}")
    lines += [
        f"Environment=SPARK_DAEMON_HOME={home()}",
        f"WatchdogSec={m.watchdog_seconds}",
        f"TimeoutStartSec={max(60, m.watchdog_seconds)}",
        "TimeoutStopSec=30",
        "Restart=on-failure",
        "RestartSec=10",
        "UMask=0077",
        "",
        "# Resources",
        f"CPUWeight={m.resources.cpu_weight}",
        f"MemoryMax={m.resources.memory_max_mb}M",
        f"TasksMax={m.resources.tasks_max}",
        f"IOSchedulingClass={m.resources.io_class}",
        "Nice=10",
        "",
        "# Filesystem: everything read-only except the output directory; denied paths invisible",
        "ProtectSystem=strict",
        "ProtectHome=read-only",
        f"ReadWritePaths={out}",
    ]
    if ro:
        lines.append("ReadOnlyPaths=" + " ".join(f"-{p}" for p in ro))
    lines += [
        "InaccessiblePaths=" + " ".join(f"-{p}" for p in deny),
        "PrivateTmp=yes",
        "PrivateDevices=yes",
        "ProtectProc=invisible",
        "",
        "# Network: none (manifest network.mode = none)",
        "PrivateNetwork=yes",
        "IPAddressDeny=any",
        "RestrictAddressFamilies=AF_UNIX",
        "",
        "# Privileges and kernel",
        "NoNewPrivileges=yes",
        "CapabilityBoundingSet=",
        "AmbientCapabilities=",
        "ProtectKernelTunables=yes",
        "ProtectKernelModules=yes",
        "ProtectKernelLogs=yes",
        "ProtectControlGroups=yes",
        "ProtectClock=yes",
        "ProtectHostname=yes",
        "RestrictNamespaces=yes",
        "RestrictRealtime=yes",
        "RestrictSUIDSGID=yes",
        "LockPersonality=yes",
        "MemoryDenyWriteExecute=yes",
        "RemoveIPC=yes",
        "KeyringMode=private",
        "SystemCallArchitectures=native",
        "SystemCallFilter=@system-service",
        "SystemCallFilter=~@privileged @resources",
        "SystemCallErrorNumber=EPERM",
        "",
        "[Install]",
        f"WantedBy={'multi-user.target' if system else 'default.target'}",
        "",
    ]
    return "\n".join(lines)


def lint(unit_text: str) -> list:
    """Directives every generated unit must carry. Returns the missing ones."""
    present = [line.strip() for line in unit_text.splitlines() if not line.lstrip().startswith("#")]
    return [d for d in REQUIRED_DIRECTIVES if not any(line.startswith(d) for line in present)]


def install_plan(m, *, root: str, python: str = "/usr/bin/python3") -> str:
    name = unit_name(m)
    out = expand(m.output_dir)
    reads = [expand(p) for p in m.reads]
    lines = [
        f"# Install plan for {name}. Nothing below has been run.",
        "# A human runs it after the battery passes and activation is approved (Class C).",
        f"# Generated by spark-daemon-pattern {VERSION}; manifest sha256 {m.sha256}.",
        "",
    ]
    entry = os.path.join(root, "bin", "spark-daemon")
    lines += [
        "# 0. The conformance battery must print RESULT: PASS for this exact manifest and daemon.py:",
        f"python3 -I -B {entry} battery --manifest {os.path.abspath(m.path)}",
        "",
    ]
    if m.run_as.unit == "system":
        user = m.run_as.user
        lines += [
            "# The service user must be able to read the pattern and this daemon's folder, and reach the",
            "# output directory. Installing the pattern and daemon folders root-owned and read-only (for",
            "# example under /opt) is simplest; an output directory under a home directory also needs",
            "# traverse (x) permission on each parent. Decide these per path.",
            f"sudo useradd --system --no-create-home --shell /usr/sbin/nologin {user}",
            f"sudo install -d -m 0700 -o {user} -g {user} {out}",
            "# Read access: the service user must be able to read each path below. Decide per path;",
            "# never grant anything under ~/spark-core/data or ~/spark-governance/history.",
        ]
        lines += [f"#   {p}" for p in reads]
        lines += [
            f"python3 -I -B {os.path.join(root, 'bin', 'spark-daemon')} unit --manifest {os.path.abspath(m.path)} > {name}",
            f"sudo install -m 0644 {name} /etc/systemd/system/{name}",
            f"sudo systemd-analyze security --threshold=20 {name}",
            "sudo systemctl daemon-reload",
            f"sudo systemctl enable --now {name}",
            f"systemctl status {name}    # READY and the last watchdog ping",
        ]
    else:
        lines += [
            "loginctl enable-linger \"$USER\"    # so the unit survives logout (Observer v0.3 section 3.4)",
            f"python3 -I -B {os.path.join(root, 'bin', 'spark-daemon')} unit --manifest {os.path.abspath(m.path)} > ~/.config/systemd/user/{name}",
            f"systemd-analyze --user security --threshold=20 {name}",
            "systemctl --user daemon-reload",
            f"systemctl --user enable --now {name}",
        ]
    return "\n".join(lines)
